# Generated by Django 6.0 on 2025-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForgeSkill', '0004_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idiomas',
            field=models.TextField(blank=True, help_text='Ej: Español (Nativo), Inglés (B2)', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_estudio',
            field=models.TextField(blank=True, help_text='Ej: Licenciatura en Ingeniería, Diplomado en Python', null=True),
        ),
    ]
