# Generated by Django 6.0 on 2025-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForgeSkill', '0005_perfil_idiomas_perfil_nivel_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='limite_miembros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='progreso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
