# Generated by Django 6.0 on 2025-12-10 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForgeSkill', '0008_proyectoactividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='habilidades_requeridas',
            field=models.TextField(blank=True, help_text='Ej: Liderazgo, Comunicación, Pensamiento crítico', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lenguajes_programacion',
            field=models.TextField(blank=True, help_text='Ej: Python, JavaScript, SQL', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='PDF, imagen o archivo comprimido como evidencia', null=True, upload_to='evidencias_tareas/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='completado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la actividad', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='conocimientos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='conocimientos',
            field=models.TextField(blank=True, help_text='Ej: Python, JavaScript, Django, React, SQL', null=True),
        ),
    ]
