# Generated by Django 6.0 on 2025-12-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForgeSkill', '0009_proyecto_habilidades_requeridas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado_retraso',
            field=models.CharField(choices=[('a_tiempo', 'A tiempo'), ('en_retraso', 'En retraso'), ('entregado_tarde', 'Entregado tarde')], default='a_tiempo', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite de entrega', null=True),
        ),
    ]
